#!/bin/bash

# Fill playlists

xmms2 playlist clear 01 ; xmms2 add -p 01 /home/pi/audio/01/* ; xmms2 playlist sort -p 01
xmms2 playlist clear 02 ; xmms2 add -p 02 /home/pi/audio/02/* ; xmms2 playlist sort -p 02
xmms2 playlist clear 03 ; xmms2 add -p 03 /home/pi/audio/03/* ; xmms2 playlist sort -p 03
xmms2 playlist clear 04 ; xmms2 add -p 04 /home/pi/audio/04/* ; xmms2 playlist sort -p 04
xmms2 playlist clear 05 ; xmms2 add -P -p 05 /home/pi/audio/05/kiraka.m3u
xmms2 playlist clear 06 ; xmms2 add -p 06 /home/pi/audio/06/* ; xmms2 playlist sort -p 06

# Switch on status led

gpio mode 26 output
gpio write 26 1

# Define GPIO pins

led01="4"
led02="7"
led03="21"
led04="24"
led05="29"
led06="28"

pin_button01="1"
pin_button02="3"
pin_button03="22"
pin_button04="23"
pin_button05="25"
pin_button06="27"
pin_button_prev="5"
pin_button_next="6"


# Set LED GPIO pins to output mode

gpio mode $led01 output
gpio mode $led02 output
gpio mode $led03 output
gpio mode $led04 output
gpio mode $led05 output
gpio mode $led06 output

# Set all GPIO pins to 0

gpio write $led01 0
gpio write $led02 0
gpio write $led03 0
gpio write $led04 0
gpio write $led05 0
gpio write $led06 0

gpio mode $pin_button01 output ; gpio write $pin_button01 0 ; gpio mode $pin_button01 input
gpio mode $pin_button02 output ; gpio write $pin_button02 0 ; gpio mode $pin_button02 input
gpio mode $pin_button03 output ; gpio write $pin_button03 0 ; gpio mode $pin_button03 input
gpio mode $pin_button04 output ; gpio write $pin_button04 0 ; gpio mode $pin_button04 input
gpio mode $pin_button05 output ; gpio write $pin_button05 0 ; gpio mode $pin_button05 input
gpio mode $pin_button06 output ; gpio write $pin_button06 0 ; gpio mode $pin_button06 input
gpio mode $pin_button_prev output ; gpio write $pin_button_prev 0 ; gpio mode $pin_button_prev input
gpio mode $pin_button_next output ; gpio write $pin_button_next 0 ; gpio mode $pin_button_next input

# Function read playlist history

typeset -i history_track_nr
typeset -i history_playtime_min
typeset -i history_playtime_sec
typeset -i history_position

read_playlist_history () {
        history_track=$(grep "track" /home/pi/audioplayer/.pls_history/pls$active_playlist_nr)
        history_track_nr=${history_track##track: }
        history_playtime=$(grep "playtime" /home/pi/audioplayer/.pls_history/pls$active_playlist_nr)
        history_playtime=${history_playtime##playtime: }
        history_playtime_min=${history_playtime%:*}
        history_playtime_sec=${history_playtime#*:}
        history_position=60*$history_playtime_min+$history_playtime_sec
                        }


# Start loop

while true
do

# Define variables

active_playlist=$(xmms2 playlist list | grep "*")
active_playlist_nr=${active_playlist:2:2}

button01=$(gpio read $pin_button01)
button02=$(gpio read $pin_button02)
button03=$(gpio read $pin_button03)
button04=$(gpio read $pin_button04)
button05=$(gpio read $pin_button05)
button06=$(gpio read $pin_button06)

button_prev=$(gpio read $pin_button_prev)
button_next=$(gpio read $pin_button_next)

current_playtime=$(xmms2 current -f '${playtime}')
current_playtime_min=${current_playtime:0:2}
current_playtime_sec=${current_playtime:3:2}


# Button 1

if [ "$button01" = "1" ]
	then

       	gpio write $led02 0
        gpio write $led03 0
        gpio write $led04 0
        gpio write $led05 0
        gpio write $led06 0

	status_led01=$(gpio read $led01)

if [ "$status_led01" = "0" ]
	then
	gpio write $led01 1
fi

if [ "$active_playlist_nr" != "01" ]
	then
	active_playlist_nr="01"
	xmms2 playlist switch 01
	read_playlist_history
	xmms2 pause
	xmms2 jump $history_track_nr
	xmms2 seek $history_position
	xmms2 play
	else
	xmms2 toggle
fi


# Button 2

elif [ "$button02" = "1" ]
	then

        gpio write $led01 0
        gpio write $led03 0
        gpio write $led04 0
        gpio write $led05 0
        gpio write $led06 0

        status_led02=$(gpio read $led02)

if [ "$status_led02" = "0" ]
        then
        gpio write $led02 1
fi

if [ "$active_playlist_nr" != "02" ]
        then
        xmms2 playlist switch 02
	xmms2 stop
        xmms2 jump 1
	xmms2 play
	else
	xmms2 toggle
fi


# Button 3

elif [ "$button03" = "1" ]
        then

        gpio write $led01 0
        gpio write $led02 0
        gpio write $led04 0
        gpio write $led05 0
        gpio write $led06 0

        status_led03=$(gpio read $led03)

if [ "$status_led03" = "0" ]
        then
        gpio write $led03 1
fi

if [ "$active_playlist_nr" != "03" ]
        then
        xmms2 playlist switch 03
        xmms2 stop
        xmms2 jump 1
        xmms2 play
        else
        xmms2 toggle
fi


# Button 4

elif [ "$button04" = "1" ]
	then

	gpio write $led01 0
        gpio write $led02 0
        gpio write $led03 0
        gpio write $led05 0
        gpio write $led06 0

        status_led04=$(gpio read $led04)

if [ "$status_led04" = "0" ]
        then
        gpio write $led04 1
fi

if [ "$active_playlist_nr" != "04" ]
        then
        xmms2 playlist switch 04
        xmms2 stop
        xmms2 jump 1
        xmms2 play
        else
        xmms2 toggle
fi


# Button 5

elif [ "$button05" = "1" ]
        then

        gpio write $led01 0
        gpio write $led02 0
        gpio write $led03 0
        gpio write $led04 0
        gpio write $led06 0

        status_led05=$(gpio read $led05)

if [ "$status_led05" = "0" ]
        then
        gpio write $led05 1
fi

if [ "$active_playlist_nr" != "05" ]
        then
        xmms2 playlist switch 05
        xmms2 stop
        xmms2 jump 1
        xmms2 play
        else
        xmms2 toggle
fi


# Button 6

elif [ "$button06" = "1" ]
        then

        gpio write $led01 0
        gpio write $led02 0
        gpio write $led03 0
        gpio write $led04 0
        gpio write $led05 0

        status_led06=$(gpio read $led06)

if [ "$status_led06" = "0" ]
        then
        gpio write $led06 1
fi

if [ "$active_playlist_nr" != "06" ]
        then
        xmms2 playlist switch 06
        xmms2 stop
        xmms2 jump 1
        xmms2 play
        else
        xmms2 toggle
fi


# Button previous title

elif [ "$button_prev" = "1" ]
	then

	if [ $current_playtime_min -eq "00" -a $current_playtime_sec -lt "10" ]
		then
		xmms2 prev > /dev/null 2>&1
		else
		xmms2 seek 00:00
fi


# Button next title

elif [ "$button_next" = "1" ]
	then
	xmms2 next > /dev/null 2>&1


fi

done
